# Generated by Django 5.0.2 on 2025-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Ожидает оплаты'), ('A', 'Оплачен'), ('C', 'Отменён')], default='P', max_length=1)),
                ('payment', models.CharField(choices=[('H', 'При получении'), ('C', 'Картой')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
