# Generated by Django 5.0.2 on 2025-04-17 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Ожидает оплаты'), ('A', 'Оплачен'), ('C', 'Отменён')], default='P', max_length=1)),
                ('payment', models.CharField(choices=[('H', 'При получении'), ('C', 'Картой')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchandise', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
