# Generated by Django 5.0.2 on 2025-10-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальная цена')),
                ('bid_step', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Шаг торгов')),
                ('start_time', models.DateTimeField(verbose_name='Время начала аукциона')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания аукциона')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Запланирован'), (2, 'Активен'), (3, 'Завершён'), (4, 'Отменён')], default=1)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='books.book')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
