# Generated by Django 5.0.2 on 2025-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('author', models.PositiveSmallIntegerField(choices=[(1, 'Ф.М. Достоевский'), (2, 'Г.Ф. Лавкрафт'), (3, 'А.С. Пушкин')], verbose_name='Автор')),
                ('year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('publisher', models.PositiveSmallIntegerField(choices=[(1, 'Издательство А'), (2, 'Издательство Б')], verbose_name='Издательство')),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'Отличное'), (2, 'Хорошее'), (3, 'Удовлетворительное')], verbose_name='Состояние')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books_photos', verbose_name='Фото книги')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'К продаже'), (2, 'Продано'), (3, 'На аукционе'), (4, 'Заблокировано')], verbose_name='Статус книги')),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Мемуары'), (2, 'История'), (3, 'Фантастика')], verbose_name='Жанр')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Художественная'), (2, 'Учебная'), (3, 'Техническая')], verbose_name='Вид книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
