# Generated by Django 5.0.2 on 2025-10-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
